In [1]:
#importing library 
import numpy as np 
# numpy -> numerical python
import sys

------------------------------------ Data Types and Size -----------------------------------------------

In [ ]:
#use np.array() function to create array- n dimension array can be ccreated 
arr = np.array ([1,2,3,4,5]) 
print(arr)

[1 2 3 4 5]


In [ ]:
#get dimensions using <arr_nam>.ndim method
arr.ndim

1

In [4]:
#get shape using <arr_name>.shape method
arr.shape

(5,)

In [8]:
arr2= np.array([[9.0,2.0,3.0], [8.0,7.0,4.0]])
print(arr2)

arr2.ndim

[[9. 2. 3.]
 [8. 7. 4.]]


2

In [9]:
arr2.shape

(2, 3)

In [10]:
#to get type use .dtype method 
arr2.dtype

dtype('float64')

In [11]:
#we can specify what data type we want elements to be we can do it explicitly during initialisation
arr3=np.array([2,4,6,8,10], dtype='int16')
arr3.dtype

dtype('int16')

In [12]:
#we can get item size in bytes by using .itemsize method 
arr2.itemsize

8

In [13]:
#we can get the total size of the array by .nbytes method 
arr2.nbytes

48

WORKING WITHIN THE ARRAY 

In [17]:
#get a specific element using [row, column]
print(arr2[1,2])
#indexing starts from 0

4.0


In [19]:
#get a specific row or column using basic slicing 
print(arr2[0, :])
print(arr2[:, 1])

[9. 2. 3.]
[2. 7.]


In [ ]:
#changing specific elements
arr3[4]=20
print(arr3)

[ 2  4  6  8 20]


INITIALIZING DIFFERENT TYPES OF ARRAY

In [ ]:
#ALL OS MATRIX - use .zeros(<dimension>) function
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#all 1s use np.ones(<dimension>)
np.ones((3,3), dtype='int16')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [ ]:
#a matrix full of a specific number
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [24]:
#array of random values
np.random.rand(4,4)

array([[0.15335929, 0.34408896, 0.03129733, 0.43415463],
       [0.20321835, 0.80796461, 0.78242845, 0.80467336],
       [0.73744701, 0.40688316, 0.34473241, 0.86077778],
       [0.15155095, 0.88807913, 0.81367142, 0.32771517]])

In [ ]:
#array of random integer values using np.random.randint(low, high=None, size=None, dtype=int)
np.random.randint(7, size= (3,3))

array([[5, 6, 2],
       [5, 6, 5],
       [3, 3, 5]], dtype=int32)

In [26]:
#identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr4= np.array([[1,2,3]])
#this will repeat the numbers of the array as manytimes as you specify it 
#axis=0 -> row wise 
#aixs =1 -> coulmn wise 
arr5= np.repeat(arr4, 3, axis =0)
arr5

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
#printing a custom matrix
'''
  1 1 1 1 1 
  1 0 1 0 1
  1 0 1 0 1
  1 0 1 0 1
  1 1 1 1 1'''

one= np.ones((5,5))
zero= np.zeros((3,3))

#this means in evry row we go to the second element and change it to 1
zero[: ,1]= 1
one[1:4, 1 :4]= zero
print(one)

[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]]
