In [1]:
import numpy as np

In [17]:
#we can generate an array from a text file given data is continuous 

file= np.genfromtxt('C:\\Users\\Neha\\Desktop\\DataScience\\data.txt', delimiter=',')

#since by default it takes float we can convert it to the data type we want
file= file.astype('int32')
print (file)

[[  1   2   8   4   5   9  52  52  85 859   5  89  52  52  58   5   5]
 [ 78  45  96  48   5 585   5   8   5   9 563   9   8   8  78  95  89]
 [  1   2   3   4   5   6   7   8   9   0   1 242   2  43  23  32 343]]


BOOLEAN MASKING AND ADVANCED INDEXING 

In [9]:
#where in file is value > 50
file > 50

array([[False, False, False, False, False, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False, False],
       [ True, False,  True, False, False,  True, False, False, False,
        False,  True, False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False,  True]])

In [20]:
file [file > 50]


array([ 52,  52,  85, 859,  89,  52,  52,  58,  78,  96, 585, 563,  78,
        95,  89, 242, 343], dtype=int32)

In [21]:
#we can index with a list in numpy such as
arr= np.array([1,2,3,4,5,6,7,8,9]) 
print(arr[[1,2,8]])

[2 3 9]


In [ ]:
#check if any specific condition is true in a  row or column 
np.any(file > 100, axis =0)
#this tells that if in each column whether we have any value greter than 100

array([False, False, False, False, False,  True, False, False, False,
        True,  True,  True, False, False, False, False,  True])

In [23]:
( (file > 50) & (file >100))

array([[False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False,  True]])

In [ ]:
'''
    1 2 3 4 5 
    6 7 8 9 10 
    11 12 13 14 15 
    16 17 18 19 20
    21 22 23 24 25 
    26 27 28 29 30
    '''
#ques: how would you index such that you get 11, 12, 16 and 17?

In [27]:
#answer
row1= np.array([1,2,3,4, 5])
row2=row1 +5
row3=row2 +5
row4=row3 +5
row5=row4+5

matrix= np.vstack([row1,row2,row3,row4,row5])
print(matrix)

#indexing 
print(matrix[ 2 :4 , 0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[11 12]
 [16 17]]


In [28]:
#when you do indexing by list in a matrix we write the row in onw list and column in another list 
print(matrix[[0,1,2,3], [1,2,3,4]])

[ 2  8 14 20]


In [29]:
print(matrix[[0,3,4], 3:])

[[ 4  5]
 [19 20]
 [24 25]]
