In [2]:
import numpy as np

In [3]:
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#we can do element wise operations 
arr2= arr +2
print (arr2)
arr3= arr * 2
print(arr3)

[3 4 5 6 7]
[ 2  4  6  8 10]


In [6]:
arr4=np.array([1,1,2,3,0])
arr +arr4

array([2, 3, 5, 7, 5])

In [7]:
#you can also take trigo values 
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [8]:
mat1 = np.ones((2,3))
mat2= np.full((3,2), 2)
print (mat1)
print(mat2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [9]:
#matrix multiplication 
np.matmul(mat1, mat2)

array([[6., 6.],
       [6., 6.]])

In [11]:
mat3= np.identity(3)

#find determinant 
print(np.linalg.det(mat3))

1.0


STATISTICS  

In [12]:
np.mean(arr)

np.float64(3.0)

In [13]:
#mqax and min 
print(np.min(arr))
print(np.max(arr))

1
5


In [17]:
print(np.sum(arr))
#if you want a row sum or column sum then you can specify that too 
#column summed up 
print(np.sum(mat1 ,axis=0))

#row summed up 
print(np.sum(mat1, axis =1))



15
[2. 2. 2.]
[3. 3.]


In [19]:
#reshape an existing array 
mat4= mat2.reshape((2,3))
mat4

array([[2, 2, 2],
       [2, 2, 2]])

In [24]:
#stacking vectors or matrices
print(np.vstack([arr, arr2,arr3]))
print(np.hstack((arr,arr2,arr3)))

[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 2  4  6  8 10]]
[ 1  2  3  4  5  3  4  5  6  7  2  4  6  8 10]
